//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipOtoparkSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BosOlans
    {
        public int KonumId { get; set; }
        public string KonumAdi { get; set; }
    }
}
