//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipOtoparkSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KasaBilgisi
    {
        public int KasaID { get; set; }
        public int VardiyaID { get; set; }
        public int AylikBorc { get; set; }
        public int EkUcret { get; set; }
        public int ToplamBorc { get; set; }
        public int OdenenBorc { get; set; }
    }
}
