//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipOtoparkSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veritabanil : DbContext
    {
        public veritabanil()
            : base("name=veritabanil")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BosOlans> BosOlans { get; set; }
        public virtual DbSet<EkSureBilgisi> EkSureBilgisi { get; set; }
        public virtual DbSet<KasaBilgisi> KasaBilgisi { get; set; }
        public virtual DbSet<KonumBilgisi> KonumBilgisi { get; set; }
        public virtual DbSet<MusteriAylıkBilgisi> MusteriAylıkBilgisi { get; set; }
        public virtual DbSet<MusteriGunlukBilgisi> MusteriGunlukBilgisi { get; set; }
        public virtual DbSet<TarifeBilgisi> TarifeBilgisi { get; set; }
        public virtual DbSet<VardiyaBilgisi> VardiyaBilgisi { get; set; }
        public virtual DbSet<Yonetici> Yonetici { get; set; }
    }
}
