//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipOtoparkSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAylıkBilgisi
    {
        public int AylikID { get; set; }
        public string APlakaNo { get; set; }
        public string TcNo { get; set; }
        public string AdSoyad { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Renk { get; set; }
        public int KonumID { get; set; }
        public int TaifeID { get; set; }
    }
}
