//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakipOtoparkSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VardiyaBilgisi
    {
        public int VardiyaID { get; set; }
        public int AylikID { get; set; }
        public int GunlukID { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public System.DateTime GecenSure { get; set; }
        public int SureID { get; set; }
    }
}
